### ISSUE TITLE
run(["gifsicle", "-U", sys.argv[1]], stdout=tmpfile)

### ISSUE THREAD

**Issue by MycroftBrooks** [bodqhrohro/giftolottie#19]
![Screenshot_1](https://user-images.githubusercontent.com/57303529/194672780-56ac6736-5e20-4f6a-9136-eac83301b680.png)

**Comment by MycroftBrooks** [comment]
how to fix this?

**Comment by bodqhrohro** [comment]
You didn't specify the file name to be processed.
