### ISSUE TITLE
Telegram bot

### ISSUE THREAD

**Issue by evpix** [bodqhrohro/giftolottie#6]
Will Telegram bot appear to convert gif to tgs?
You mentioned this in your telegram channel description: https://t.me/retrostickers

> There are GIFs converted to animated stickers.
> 
> Converter: https://github.com/bodqhrohro/giftolottie/
> Will likely be a bot soon.

**Comment by mykelangelo** [comment]
So, is there a bot? Or has it been abandoned?

**Comment by evpix** [comment]
There is no bot for Telegram.  You can see that the bot was not created.

**Comment by mykelangelo** [comment]
Oh, a pity. But the desktop version works?

**Comment by evpix** [comment]
Desktop version more or less stable for use. But there may be bugs and errors. You can see this by looking at the list [issues](https://github.com/bodqhrohro/giftolottie/issues).
