### ISSUE TITLE
ModuleNotFoundError: No module named 'pkg_resources'

### ISSUE THREAD

**Issue by iComputerfreak** [bodqhrohro/giftolottie#8]
I get the following error when executing your code:

```
$ python3 read.py input.gif output.tgs
Traceback (most recent call last):
  File "read.py", line 8, in <module>
    import vendor.gif2numpy
  File "/Users/jonasfrey/Desktop/temp/giftolottie/vendor/gif2numpy.py", line 30, in <module>
    from pkg_resources import parse_version
ModuleNotFoundError: No module named 'pkg_resources'
```

I uploaded my Terminal output to Pastebin, so you can see the exact steps I took to install the dependencies and your script and see if I made any errors there: [https://pastebin.com/qnBsDLcY](https://pastebin.com/qnBsDLcY)

I was trying to execute the script on macOS 10.15.4 and was therefore using HomeBrew to install gifsicle.

**Comment by bodqhrohro** [comment]
Possibly a setuptools problem, see https://stackoverflow.com/questions/7446187/no-module-named-pkg-resources

**Comment by iComputerfreak** [comment]
Since I can no longer reproduce the original error, I'm going to close this issue.
